---
title: "Load images and predict score"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{predict}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Load libraries
```{r}
library(AutoCDAScorer)
```


# Load model and images. View example image

Need to change this to a cdascorer file in extdata

```{r}
# Load original images
original_dataset <- load_images("/Users/jowillia/Documents/GitHub/Bulletproof_Models/data/cropped_images", image_size=64)
show_test_image(original_dataset)

# Load new images
new_dataset <- load_images("/Users/jowillia/Documents/GitHub/Bulletproof_Models/data/bio_test", image_size=64)
show_test_image(new_dataset)
```

# Diagnostic plots
Replace interactive plot with all-against-all plots. Here are three types: target plots, contour plots, and convex hull plots.
```{r}
target_plot <- diagnostic_pca(
  "base_cnn",
  new_dataset,
  num_pcs = 5,
  plot_type = "target",
  num_ellipses = 3
)
target_plot

contour_plot <- diagnostic_pca(
  "base_cnn",
  new_dataset,
  num_pcs = 5,
  plot_type = "density",
  num_bins = 5
)
contour_plot

convexhull_plot <- diagnostic_pca(
  "base_cnn",
  new_dataset,
  num_pcs = 5,
  plot_type = "convexhull"
)
convexhull_plot
```
