name: Test Coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfreetype6-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff-dev \
            libxt-dev \
            libgit2-dev \
            libz-dev \
            libgmp-dev \
            libblas-dev \
            liblapack-dev \
            libopenblas-dev \
            libfribidi-dev \
            libmagick++-dev
      - name: Install dependencies
        run: |
          install.packages(c("covr", "devtools", "mockery"))
        shell: Rscript {0}
      - name: Install AutoCDAScorer
        run: |
          devtools::install()
        shell: Rscript {0}
      - name: Generate coverage report
        run: |
          coverage <- covr::package_coverage()
          covr::to_lcov(coverage, filename = "coverage.lcov")
        shell: Rscript {0}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.lcov
          flags: unittests
          name: R Package Coverage


