name: Test Python and Numpy with Reticulate

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-python-numpy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

          # Check where Python is installed
          echo "Python location: $(which python)"
          python --version

          # Check where numpy is installed
          python -c "import numpy; print('Numpy location:', numpy.__file__)"

      - name: Install system dependencies (for R and png)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfreetype6-dev \
            libpng-dev  # Install missing png library

      - name: Install reticulate in R
        run: |
          install.packages("reticulate")
        shell: Rscript {0}

      - name: Test Python with Reticulate
        run: |
          library(reticulate)

          # Set the Python path (adjust if needed)
          reticulate::use_python("/opt/hostedtoolcache/Python/3.11.11/x64/bin/python", required = TRUE)

          # Run py_config() to check Python configuration
          py_config()

          # Check Python availability
          if (reticulate::py_available(initialize = TRUE)) {
            print("Python is available.")
          } else {
            print("Python is NOT available.")
          }

          # Check numpy availability
          print("Checking numpy availability...")
          if (reticulate::py_module_available("numpy")) {
            print("Numpy is available.")
          } else {
            print("Numpy is NOT available.")
          }
        shell: Rscript {0}
