name: R CMD check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up R ${{ matrix.config.r }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: "stable"

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: "--no-manual --as-cran"
          error-on: "never"
          check-dir: "check"
          upload-snapshots: true
